# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_andar_number', models.IntegerField(default=0)),
                ('agency_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Doner_Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doner_engagement', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Geo_Focus_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('percent_of_focus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_andar_number', models.IntegerField(default=0)),
                ('program_name', models.CharField(max_length=128)),
                ('grant_start_date', models.DateField()),
                ('grant_end_date', models.DateField()),
                ('program_discription', models.CharField(max_length=128)),
                ('program_planner', models.CharField(max_length=128)),
                ('funds', models.CharField(max_length=128)),
                ('focus_area', models.CharField(max_length=128)),
                ('strategic_outcome', models.CharField(max_length=128)),
                ('funding_stream', models.CharField(max_length=128)),
                ('allocation', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2016)),
                ('website', models.CharField(max_length=128)),
                ('agency_andar_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uw_dashboard.Agencies')),
            ],
        ),
        migrations.CreateModel(
            name='Program_Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('element_name', models.IntegerField(default=0)),
                ('specific_element', models.IntegerField(default=0)),
                ('program_andar_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uw_dashboard.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Target_Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_Population', models.CharField(max_length=128)),
                ('program_andar_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uw_dashboard.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('early_years', models.IntegerField(default=0)),
                ('middle_years', models.IntegerField(default=0)),
                ('seniors', models.IntegerField(default=0)),
                ('parent_caregivers', models.IntegerField(default=0)),
                ('families', models.IntegerField(default=0)),
                ('contacts', models.IntegerField(default=0)),
                ('meals_snacks', models.IntegerField(default=0)),
                ('counselling_sessions', models.IntegerField(default=0)),
                ('mentors_tutors', models.IntegerField(default=0)),
                ('workshops', models.IntegerField(default=0)),
                ('volunteers', models.IntegerField(default=0)),
                ('program_andar_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uw_dashboard.Program')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='program_andar_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uw_dashboard.Program'),
        ),
        migrations.AddField(
            model_name='geo_focus_area',
            name='program_andar_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uw_dashboard.Program'),
        ),
        migrations.AddField(
            model_name='doner_engagement',
            name='program_andar_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uw_dashboard.Program'),
        ),
    ]
