# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uw_dashboard', '0002_databasereader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_area', models.CharField(max_length=512)),
                ('target_population', models.CharField(max_length=512)),
                ('program_elements', models.CharField(max_length=512)),
                ('city_groupings', models.CharField(max_length=512)),
                ('geographic_focus_area', models.CharField(max_length=512)),
                ('donor_engagement', models.CharField(max_length=512)),
                ('money_invested', models.CharField(max_length=512)),
                ('funding_year', models.CharField(max_length=512)),
            ],
        ),
    ]
