# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uw_dashboard', '0002_auto_20170325_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50)),
                ('overwrite', models.BooleanField()),
                ('year', models.CharField(max_length=20)),
                ('upload_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
